### ISSUE TITLE
PHP 8.0 Support

### ISSUE THREAD

**Issue by prdatur** [allansun/openapi-parser#2]
Hi,

Tried to use this with php8.0
But with the current `composer,json` is 7.4 only supported. Any chance to push this up to >= 7.4? or like others do 7.4|8.0 / 8.1 ?

**Comment by allansun** [comment]
Done! Give it a try to update to version 2.1.4.2

**Comment by allansun** [comment]
I will close this issue by commit 2fe1a88167e8d543344843978e909a586f329b1b
